export type FontDef = { name: string; cat: string; weights?: string }

export const FONT_CATS = ['Sans-Serif','Serif','Display','Handwriting','Monospace','Rounded']

export const FONTS: FontDef[] = [
  // Sans-Serif
  { name:'Inter',              cat:'Sans-Serif' },
  { name:'Jost',               cat:'Sans-Serif' },
  { name:'Plus Jakarta Sans',  cat:'Sans-Serif' },
  { name:'DM Sans',            cat:'Sans-Serif' },
  { name:'Outfit',             cat:'Sans-Serif' },
  { name:'Syne',               cat:'Sans-Serif' },
  { name:'Manrope',            cat:'Sans-Serif' },
  { name:'Rubik',              cat:'Sans-Serif' },
  { name:'Work Sans',          cat:'Sans-Serif' },
  { name:'Raleway',            cat:'Sans-Serif' },
  { name:'Montserrat',         cat:'Sans-Serif' },
  { name:'Open Sans',          cat:'Sans-Serif' },
  { name:'Lato',               cat:'Sans-Serif' },
  { name:'Barlow',             cat:'Sans-Serif' },
  { name:'Space Grotesk',      cat:'Sans-Serif' },
  { name:'Nunito Sans',        cat:'Sans-Serif' },
  { name:'Source Sans 3',      cat:'Sans-Serif' },
  { name:'Ubuntu',             cat:'Sans-Serif' },
  { name:'Mulish',             cat:'Sans-Serif' },
  { name:'Karla',              cat:'Sans-Serif' },
  { name:'Hind',               cat:'Sans-Serif' },
  { name:'Fira Sans',          cat:'Sans-Serif' },
  { name:'Cabin',              cat:'Sans-Serif' },
  { name:'Noto Sans',          cat:'Sans-Serif' },
  { name:'PT Sans',            cat:'Sans-Serif' },
  { name:'Prompt',             cat:'Sans-Serif' },
  { name:'Exo 2',              cat:'Sans-Serif' },
  { name:'Heebo',              cat:'Sans-Serif' },
  { name:'Varela Round',       cat:'Sans-Serif' },
  { name:'Arimo',              cat:'Sans-Serif' },
  { name:'Asap',               cat:'Sans-Serif' },
  { name:'Dosis',              cat:'Sans-Serif' },
  { name:'Encode Sans',        cat:'Sans-Serif' },
  { name:'Overpass',           cat:'Sans-Serif' },
  { name:'Schibsted Grotesk',  cat:'Sans-Serif' },
  { name:'Figtree',            cat:'Sans-Serif' },
  { name:'Albert Sans',        cat:'Sans-Serif' },
  { name:'Bricolage Grotesque',cat:'Sans-Serif' },
  { name:'Geist',              cat:'Sans-Serif' },
  { name:'Lexend',             cat:'Sans-Serif' },
  { name:'Readex Pro',         cat:'Sans-Serif' },
  { name:'Urbanist',           cat:'Sans-Serif' },
  { name:'Red Hat Display',    cat:'Sans-Serif' },
  { name:'Be Vietnam Pro',     cat:'Sans-Serif' },
  { name:'Instrument Sans',    cat:'Sans-Serif' },
  { name:'Yantramanav',        cat:'Sans-Serif' },
  { name:'M PLUS 1p',          cat:'Sans-Serif' },
  { name:'Poppins',            cat:'Sans-Serif' },
  // Serif
  { name:'Playfair Display',   cat:'Serif' },
  { name:'Cormorant Garamond', cat:'Serif' },
  { name:'Merriweather',       cat:'Serif' },
  { name:'Lora',               cat:'Serif' },
  { name:'EB Garamond',        cat:'Serif' },
  { name:'Libre Baskerville',  cat:'Serif' },
  { name:'Crimson Text',       cat:'Serif' },
  { name:'Bitter',             cat:'Serif' },
  { name:'Cardo',              cat:'Serif' },
  { name:'Noto Serif',         cat:'Serif' },
  { name:'PT Serif',           cat:'Serif' },
  { name:'Source Serif 4',     cat:'Serif' },
  { name:'Spectral',           cat:'Serif' },
  { name:'Zilla Slab',         cat:'Serif' },
  { name:'Domine',             cat:'Serif' },
  { name:'Vollkorn',           cat:'Serif' },
  { name:'Alegreya',           cat:'Serif' },
  { name:'Charis SIL',         cat:'Serif' },
  { name:'DM Serif Display',   cat:'Serif' },
  { name:'Gloock',             cat:'Serif' },
  { name:'Instrument Serif',   cat:'Serif' },
  { name:'Libre Caslon Text',  cat:'Serif' },
  { name:'Newsreader',         cat:'Serif' },
  { name:'Bodoni Moda',        cat:'Serif' },
  { name:'Fraunces',           cat:'Serif' },
  // Display
  { name:'Oswald',             cat:'Display' },
  { name:'Bebas Neue',         cat:'Display' },
  { name:'Anton',              cat:'Display' },
  { name:'Righteous',          cat:'Display' },
  { name:'Teko',               cat:'Display' },
  { name:'Archivo Black',      cat:'Display' },
  { name:'Black Han Sans',     cat:'Display' },
  { name:'Passion One',        cat:'Display' },
  { name:'Squada One',         cat:'Display' },
  { name:'Alfa Slab One',      cat:'Display' },
  { name:'Boogaloo',           cat:'Display' },
  { name:'Lilita One',         cat:'Display' },
  { name:'Bangers',            cat:'Display' },
  { name:'Russo One',          cat:'Display' },
  { name:'Fugaz One',          cat:'Display' },
  { name:'Abril Fatface',      cat:'Display' },
  { name:'Black Ops One',      cat:'Display' },
  { name:'Exo',                cat:'Display' },
  { name:'Chakra Petch',       cat:'Display' },
  { name:'Unbounded',          cat:'Display' },
  { name:'Wallpoet',           cat:'Display' },
  { name:'Climate Crisis',     cat:'Display' },
  { name:'Big Shoulders Display', cat:'Display' },
  // Handwriting / Script
  { name:'Dancing Script',     cat:'Handwriting' },
  { name:'Great Vibes',        cat:'Handwriting' },
  { name:'Pacifico',           cat:'Handwriting' },
  { name:'Sacramento',         cat:'Handwriting' },
  { name:'Satisfy',            cat:'Handwriting' },
  { name:'Allura',             cat:'Handwriting' },
  { name:'Alex Brush',         cat:'Handwriting' },
  { name:'Pinyon Script',      cat:'Handwriting' },
  { name:'Tangerine',          cat:'Handwriting' },
  { name:'Courgette',          cat:'Handwriting' },
  { name:'Kaushan Script',     cat:'Handwriting' },
  { name:'Lobster',            cat:'Handwriting' },
  { name:'Parisienne',         cat:'Handwriting' },
  { name:'Caveat',             cat:'Handwriting' },
  { name:'Permanent Marker',   cat:'Handwriting' },
  { name:'Indie Flower',       cat:'Handwriting' },
  { name:'Shadows Into Light', cat:'Handwriting' },
  { name:'Patrick Hand',       cat:'Handwriting' },
  { name:'Kalam',              cat:'Handwriting' },
  { name:'Amatic SC',          cat:'Handwriting' },
  { name:'Rock Salt',          cat:'Handwriting' },
  { name:'Reenie Beanie',      cat:'Handwriting' },
  { name:'Just Me Again Down Here', cat:'Handwriting' },
  { name:'Qwigley',            cat:'Handwriting' },
  { name:'Meow Script',        cat:'Handwriting' },
  { name:'Waterfall',          cat:'Handwriting' },
  { name:'Whisper',            cat:'Handwriting' },
  // Monospace
  { name:'JetBrains Mono',     cat:'Monospace' },
  { name:'IBM Plex Mono',      cat:'Monospace' },
  { name:'Space Mono',         cat:'Monospace' },
  { name:'Roboto Mono',        cat:'Monospace' },
  { name:'Fira Code',          cat:'Monospace' },
  { name:'Source Code Pro',    cat:'Monospace' },
  { name:'Courier Prime',      cat:'Monospace' },
  { name:'Inconsolata',        cat:'Monospace' },
  { name:'Overpass Mono',      cat:'Monospace' },
  { name:'Share Tech Mono',    cat:'Monospace' },
  // Rounded
  { name:'Nunito',             cat:'Rounded' },
  { name:'Quicksand',          cat:'Rounded' },
  { name:'Comfortaa',          cat:'Rounded' },
  { name:'Varela Round',       cat:'Rounded' },
  { name:'Fredoka',            cat:'Rounded' },
  { name:'Nunito',             cat:'Rounded' },
  { name:'Baloo 2',            cat:'Rounded' },
  { name:'Georama',            cat:'Rounded' },
  { name:'Bubblegum Sans',     cat:'Rounded' },
]

export function buildGoogleFontsUrl(families: string[]): string {
  const unique = [...new Set(families)]
  const params = unique.map(f => `family=${f.replace(/ /g,'+')}:wght@300;400;500;600;700;800;900`).join('&')
  return `https://fonts.googleapis.com/css2?${params}&display=swap`
}

export function preloadFont(family: string): void {
  const safe = family.replace(/ /g, '+')
  const id = `gf-${safe}`
  if (document.getElementById(id)) return
  const l = document.createElement('link')
  l.id = id; l.rel = 'stylesheet'
  l.href = `https://fonts.googleapis.com/css2?family=${safe}:wght@300;400;500;600;700;800;900&display=swap`
  document.head.appendChild(l)
}
